######################################################################
# Automatically generated by qmake (3.0) ?? ????. 26 16:23:42 2015
######################################################################

TEMPLATE = app
TARGET = excel
INCLUDEPATH += .
QT += xlsx widgets printsupport gui
# Input
HEADERS += ./src/excel.h ./src/graph.h ./src/mainwindow.h 
SOURCES += ./src/excel.cpp ./src/main.cpp ./src/graph.cpp ./src/mainwindow.cpp
