######################################################################
# Automatically generated by qmake (3.0) ?? ????. 26 16:23:42 2015
######################################################################

TEMPLATE = app
TARGET = excel
INCLUDEPATH += .
QT += xlsx widgets printsupport gui
# Input
HEADERS += excel.h graph.h mainwindow.h 
SOURCES += excel.cpp main.cpp graph.cpp mainwindow.cpp
